pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import Caelestia
import qs.services
import qs.config

Singleton {
    id: root

    property alias enabled: props.enabled

    readonly property string coreConf: `${Quickshell.env("HOME")}/.config/mango/mango_core.conf`
    readonly property string modeConf: `${Quickshell.env("HOME")}/.config/mango/caelestia_gamemode.conf`
    readonly property string modeSource: "source=~/.config/mango/caelestia_gamemode.conf"

    // Mango game mode: overrides written to a sourced file (like Noctalia's
    // noctalia.conf), toggled via a source= line in mango_core.conf + reload.
    // Removing the source line restores the user's own values.
    function writeGameMode(enabled: bool): void {
        const script = `f="${root.coreConf}"; gm="${root.modeConf}"; ` +
            `if [ "$1" = on ]; then ` +
            `if [ ! -f "$gm" ]; then cat > "$gm" <<'EOF'\n` +
            `# Caelestia game mode overrides\n` +
            `# Generated by caelestia-shell - edits here persist until regenerated\n` +
            `animations=0\n` +
            `layer_animations=0\n` +
            `blur=0\n` +
            `blur_layer=0\n` +
            `shadows=0\n` +
            `layer_shadows=0\n` +
            `gappih=0\n` +
            `gappiv=0\n` +
            `gappoh=0\n` +
            `gappov=0\n` +
            `borderpx=1\n` +
            `border_radius=0\n` +
            `allow_tearing=1\n` +
            `EOF\nfi; ` +
            `grep -q '^source=.*caelestia_gamemode.conf' "$f" || printf '%s\\n' '${root.modeSource}' >> "$f"; ` +
            `else ` +
            `sed -i '/caelestia_gamemode\\.conf/d' "$f"; ` +
            `fi; ` +
            `mmsg dispatch reload_config`;
        Quickshell.execDetached(["sh", "-c", script, "sh", enabled ? "on" : "off"]);
    }

    onEnabledChanged: {
        if (!props.initialised)
            return;
        if (enabled) {
            writeGameMode(true);
            if (Config.utilities.toasts.gameModeChanged)
                Toaster.toast(qsTr("Game mode enabled"), qsTr("Disabled Mango animations, blur, gaps and shadows"), "gamepad");
        } else {
            writeGameMode(false);
            if (Config.utilities.toasts.gameModeChanged)
                Toaster.toast(qsTr("Game mode disabled"), qsTr("Mango settings restored"), "gamepad");
        }
    }

    PersistentProperties {
        id: props

        property bool enabled: false
        property bool initialised: false

        reloadableId: "gameMode"
    }

    // Initialise from the actual config file so state survives shell restarts.
    Process {
        id: initProc

        running: true
        command: ["sh", "-c", `grep -q 'caelestia_gamemode.conf' "${root.coreConf}" && printf 1 || printf 0`]
        stdout: StdioCollector {
            onStreamFinished: {
                props.enabled = text.trim() === "1";
                props.initialised = true;
            }
        }
    }

    IpcHandler {
        function isEnabled(): bool {
            return props.enabled;
        }

        function toggle(): void {
            props.enabled = !props.enabled;
        }

        function enable(): void {
            props.enabled = true;
        }

        function disable(): void {
            props.enabled = false;
        }

        target: "gameMode"
    }
}
